from pygame import Color

ARENA_RADIUS = 20
WALL_WIDTH = .8
WALL_MIN_LENGTH = 2
WALL_MAX_LENGTH = 10
WALL_COUNT = 40
WALL_HEALTH_DENSITY = 2

WALL_ALIVE_COLOR = Color("black")
WALL_ALMOST_DEAD_COLOR = Color("#1a0b6580")

PLAYER_SPAWN_RADIUS = ARENA_RADIUS / 2
